= UserModule
:toc:

== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>across-standard-modules</groupId>
			<artifactId>user-module</artifactId>
			<version>{across-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|<<integration:adminweb-entity,EntityModule>>
|optional
|In combination with `AdminWebModule` this enables the management forms in the administration UI.
|===

=== Module settings

|===
|Property |Description |Default

|===

== About the UserModule

== Integration with other modules

[[integration:adminweb-entity]]
==== EntityModule
The `UserModule` configures all its domain objects in the `EntityRegistry` if the `EntityModule` is present.  Along with
the `AdminWebModule` this will also enable the administrative management controllers for those entities.

NOTE: By default the `Permission` and `PermissionGroup` entities are `hidden` from the admin UI and can only be managed through code.  If you
want to enable UI management of those entities, you can modify the `hidden` property using a custom `EntityConfigurer`.


