= SpringSecurityAclModule
Arne Vandamme
3.0.1.RELEASE
:toc: left
:sectanchors:
:module-version: 3.0.1.RELEASE
:module-name: SpringSecurityAclModule
:module-artifact: spring-security-acl-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityAclModule

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|`SpringSecurityModule`
|required
|Provides the basic security infrastructure.

|`AcrossHibernateJpaModule`
|optional
|Activates support for ACL security entities.

|`EntityModule`
|optional
|Enables the management forms for ACL security entities.

|===

=== Module settings
This module has no specific settings.

== What's new in this version?
:numbered!:
=== 3.0.1.RELEASE
* SpringSecurityAclModule now uses a single `AclPermissionFactory` for the actual permission management
** custom permissions can be registered on this factory and made available for use in security expressions
* the first 10 permission positions (bit flags) are now reserved for Across internal use
** the 5 default permissions take up half of these positions
** applications or non-shared modules should create custom permissions on the positions > 10
* `AclPermission` has some helper methods for easily creating custom permissions: `create()` and `combine()`, with validation regarding the reserved bit range
* AclPermissionForm
** registry for registration
** ObjectIdentity.class.getName() attribute for custom identity resolver

=== 2.0.1.RELEASE
* added support for H2 database

:numbered:
== About the SpringSecurityAclModule
The `SpringSecurityAclModule` enables Access Control Lists for managing permissions.  The core service for working
with the ACLs is the `AclSecurityService` and supports management of ACLs attached to `IdBasedEntity` instances,
seamlessly integrating with other standard modules.

=== Default parent ACL
The `AclSecurityService` optionally allows setting a default parent ACL (in the form of the `IdBasedEntity`
that owns the ACL).  The default parent is attached to any newly created ACL that does not have an explicit parent
specified.

=== ACL security entities
The `SpringSecurityAclModule` packs a domain model for ACL security entities.  These are abstract database entities
that serve no other purpose than attaching an ACL to them.  They optionally take another security entity as parent,
whose ACL will then also be the parent ACL.

The ACL security entity hierarchy exactly represents the backing ACL hierarchy.  ACL security entities are usually
only developer managed and by default require the *acl take ownership* permissions to manage them through the
administrative interface.

The standard `UserModule` provides a default installation of security entities, and sets the *system* security entity
for the default parent ACL.

=== Global permissions
The `SpringSecurityAclModule` defines 3 global permissions, these are available as constants in the `AclAuthorities` interface.

.Global permission overview
|===
|Permission |Description

|*acl take ownership*
|Allows the authenticated principal to take ownership of any ACL. Also the required permission to be able
to manage ACL security entities.

|*acl modify*
|Allows the authenticated principal to modify any ACL.  This includes adding and removing ACE records but
excludes changing ownership.

|*acl audit*
|Allows the authenticated principal to modify the auditing settings of an ACL.

|===

== Known ACL permissions
The following lists the known/used ACL permissions from shared modules.

An ACL permission:

* takes a single bit position (total range is numbered from 0 to 31)
* optionally has a single character code that is used when displaying a permission pattern (eg. `\...\...\...\...\...\...\...\...\....D.WR`)
* has a unique name that can be used in expression based security (eg. `hasPermission(#object,'my-permission')`)

[discrete]
=== Reserved bit range
The first 10 bit positions are reserved for use by Across standard modules.
To avoid conflicts with this range, use `AclPermission.create()` for defining your custom permissions.

|===
|Bit position |Permission name |Code |Module

|0 |read | R |SpringSecurityAclModule
|1 |write |W |SpringSecurityAclModule
|2 |create |C |SpringSecurityAclModule
|3 |delete |D |SpringSecurityAclModule
|4 |administration |A |SpringSecurityAclModule

|===

[discrete]
=== Open bit range
The open bit range (> position 10) is meant for custom applications or modules.








